Update package.json
With the latest changes found here:

https://github.com/auth0/node-jwks-rsa/blob/master/src/wrappers/request.js#L4-L5

We need to specify http(s)-proxy-agent as a dependency, otherwise when its installed on the consumer it will fail with this error:

Error: Cannot find module 'https-proxy-agent'
Require stack:
- /Users/matthewroelle/s/account-api/packages/customer-api/node_modules/jwks-rsa/lib/wrappers/request.js
- /Users/matthewroelle/s/account-api/packages/customer-api/node_modules/jwks-rsa/lib/JwksClient.js
- /Users/matthewroelle/s/account-api/packages/customer-api/node_modules/jwks-rsa/lib/index.js